name: PR Setup Job Flow

on:
  pull_request:
    branches:
      - "**"

# Demo how to use the setup job flow
#
# In this flow, a workflow must create a separate "setup" job that initializes
# the comment by passing initialize: true. Then each other job that actually
# reports benchmark results must declare the "setup" job as a dependency in its
# "needs" array.

jobs:
  setup:
    name: Setup Tachometer Reporting
    runs-on: ubuntu-latest
    steps:
      - name: Initialize tachometer comment
        uses: andrewiggins/tachometer-reporter-action@master
        with:
          initialize: true

  bench_1:
    name: First Bench Job
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Could use this to simulate benchmark running for random number of seconds
          echo $((($RANDOM%(5000-1000))+1000))
      - name: Report Tachometer Result
        uses: andrewiggins/tachometer-reporter-action@master
        with:
          path: tests/results/test-results.json
          pr-bench-name: local-framework
          base-bench-name: base-framework

  bench_2:
    name: Second Bench Job
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Report Other Tachometer Result
        uses: andrewiggins/tachometer-reporter-action@master
        with:
          path: tests/results/other-results.json
