name: PR Single Job

on:
  pull_request:
    branches:
      - "**"

jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - name: Log GitHub Context
        run: node -e 'var github = require("@actions/github"); var context = github.context; console.log("context.issue =", JSON.stringify(context.issue, null, 2)); console.log("context.repo =", JSON.stringify(context.repo, null, 2)); console.log("context = ", JSON.stringify(context, null, 2));'
      - run: npm test
        env:
          TACH_REPORTER_SKIP_SNAPSHOT_TESTS: "true"
      - run: |
          # Could use this to simulate benchmark running for random number of seconds
          echo $((($RANDOM%(5000-1000))+1000))
      - name: Report Tachometer Result
        uses: andrewiggins/tachometer-reporter-action@main
        with:
          path: tests/results/test-results.json
          pr-bench-name: local-framework
          base-bench-name: base-framework
